version: 2.1
orbs:
  cypress: cypress-io/cypress@1.1.0

workflows:
  build-components-and-app:
    jobs:
      - cypress/install:
          build: npm run bootstrap
      - cypress/run:
          requires:
            - cypress/install
          start: npm run start:test-server
          wait-on: 'http://localhost:5000'
